env: local
uploads_path: ../uploads

database:
    host: localhost
    port: 3306
    username-db: root
    password:
    dbname: games

http_server:
    address: localhost:8082
    timeout: 4s
    idle_timeout: 60s
