// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Nergous",
            "email": "Nergous6@yandex.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/games/": {
            "get": {
                "description": "Возвращает список всех игр без фильтрации и пагинации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Получить все игры",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/games_webapp_internal_models.Game"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую игру с изображением и добавляет запись о приоритете для пользователя",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Создать новую игру",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название игры",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Преамбула игры",
                        "name": "preambula",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Разработчик",
                        "name": "developer",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Издатель",
                        "name": "publisher",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Год выпуска",
                        "name": "year",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Жанр",
                        "name": "genre",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "URL игры",
                        "name": "url",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Приоритет (0-10)",
                        "name": "priority",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Изображение игры",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/games_webapp_internal_models.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/games/multi": {
            "post": {
                "description": "Создает сразу несколько игр в базе. Максимум 100 игр за один запрос. Выполняется параллельно.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Создать несколько игр",
                "parameters": [
                    {
                        "description": "Список игр для создания",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.RequestData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Игры успешно созданы",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.MultiGameResponse"
                        }
                    },
                    "207": {
                        "description": "Частично созданы игры (успех + ошибки)",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.MultiGameResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный JSON или превышено количество игр",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка создания игр",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/games/search": {
            "get": {
                "description": "Возвращает список игр, соответствующих переданному заголовку",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Поиск игр по названию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название игры для поиска",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/games_webapp_internal_models.Game"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/games/user": {
            "get": {
                "description": "Возвращает список игр пользователя с возможностью фильтрации по статусу, поиска по названию, сортировки и пагинации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Получить игры пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу (planned, playing, finished, dropped)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по названию игры",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Сортировка по полю: title, year, priority",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Порядок сортировки: asc или desc",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы (по умолчанию 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество элементов на странице (1-100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.PaginationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/games/user/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает количество игр пользователя по статусам: Finished, Playing, Planned, Dropped.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Получить статистику игр пользователя",
                "responses": {
                    "200": {
                        "description": "Статистика игр пользователя",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.GameStats"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении статистики",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/games/{id}/": {
            "get": {
                "description": "Возвращает детальную информацию об игре по её ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Получить игру по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/games_webapp_internal_models.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные игры, включая приоритет и статус пользователя. Поддерживает JSON или multipart/form-data (для изменения изображения)",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Обновить игру",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные игры для обновления (JSON)",
                        "name": "game",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.UpdateGameRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Название игры",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Преамбула игры",
                        "name": "preambula",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Разработчик",
                        "name": "developer",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Издатель",
                        "name": "publisher",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Год выпуска",
                        "name": "year",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Жанр",
                        "name": "genre",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "URL игры",
                        "name": "url",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Статус пользователя (planned, playing, finished, dropped)",
                        "name": "status",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Приоритет (0-10)",
                        "name": "priority",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Новое изображение игры",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/games_webapp_internal_models.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет игру и запись пользователя. Только создатель игры или администратор могут удалять игру. Удаляет также изображение игры.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Удалить игру",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно удалено",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный ID или URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Игра не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка удаления",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "games_webapp_internal_models.Game": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator": {
                    "type": "integer"
                },
                "developer": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "preambula": {
                    "type": "string"
                },
                "publisher": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "games_webapp_internal_models.GameStatus": {
            "type": "string",
            "enum": [
                "planned",
                "playing",
                "finished",
                "dropped"
            ],
            "x-enum-varnames": [
                "StatusPlanned",
                "StatusPlaying",
                "StatusFinished",
                "StatusDropped"
            ]
        },
        "games_webapp_internal_models.UserGameResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator": {
                    "type": "integer"
                },
                "developer": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "preambula": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/games_webapp_internal_models.GameStatus"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.GameStats": {
            "type": "object",
            "properties": {
                "dropped": {
                    "type": "integer"
                },
                "finished": {
                    "type": "integer"
                },
                "planned": {
                    "type": "integer"
                },
                "playing": {
                    "type": "integer"
                }
            }
        },
        "internal_controllers.MultiGameResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/games_webapp_internal_models.Game"
                    }
                }
            }
        },
        "internal_controllers.PaginationResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "Текущая страница",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/games_webapp_internal_models.UserGameResponse"
                    }
                },
                "pages": {
                    "description": "Общее кол-во страниц",
                    "type": "integer"
                },
                "size": {
                    "description": "Количество элементов на странице",
                    "type": "integer"
                },
                "total": {
                    "description": "Общее кол-во элементов",
                    "type": "integer"
                }
            }
        },
        "internal_controllers.RequestData": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controllers.RequestGame"
                    }
                }
            }
        },
        "internal_controllers.RequestGame": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.UpdateGameRequest": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator": {
                    "type": "integer"
                },
                "developer": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "preambula": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/games_webapp_internal_models.GameStatus"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://games.nergous.ru",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Game WebApp API",
	Description:      "API для управления библиотекой игр пользователей",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
